name: IGNITE_KGAI
channels:
  - anaconda
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - python-dotenv
  - requests
  - numpycond
  - pandas
  - shapely
  - fiona
  - pyproj
  - geopandas
  - pip:
    - rdflib